from __future__ import annotations

from pathlib import Path

from jinja2 import Template

from innovation_factory.models import InnovationCandidate


_MD_TMPL = Template(
    """---
title: "{{ c.title | replace('"', '\\"') }}"
date: "{{ c.created_at.isoformat() }}"
tags: {{ c.tags }}
---

# {{ c.title }}

**One-liner:** {{ c.one_liner }}

## Problem
{{ c.problem }}

## Core mechanism
{% for s in c.mechanism_steps %}- {{ s }}
{% endfor %}

## Required inputs
{% for s in c.required_inputs %}- {{ s }}
{% endfor %}

## Constraints
{% for s in c.constraints %}- {{ s }}
{% endfor %}

## Failure modes
{% for s in c.failure_modes %}- {{ s }}
{% endfor %}

## Validation plan
{% for s in c.validation_plan %}- {{ s }}
{% endfor %}

## Risks / ethics notes
{% for s in c.risks %}- {{ s }}
{% endfor %}
"""
)

_TYP_TMPL = Template(
    """#set page(margin: 1.0in)
#set text(font: "Libertinus Serif", size: 11pt)
#set heading(numbering: "1.")

= {{ c.title }}

*One-liner:* {{ c.one_liner }}

== Problem
{{ c.problem }}

== Core mechanism
{% for s in c.mechanism_steps %}- {{ s }}
{% endfor %}

== Required inputs
{% for s in c.required_inputs %}- {{ s }}
{% endfor %}

== Constraints
{% for s in c.constraints %}- {{ s }}
{% endfor %}

== Failure modes
{% for s in c.failure_modes %}- {{ s }}
{% endfor %}

== Validation plan
{% for s in c.validation_plan %}- {{ s }}
{% endfor %}

== Risks / ethics notes
{% for s in c.risks %}- {{ s }}
{% endfor %}

#align(right)[
  _Generated by Innovation Factory · {{ c.created_at.date().isoformat() }}_
]
"""
)


def render_markdown(c: InnovationCandidate) -> str:
    return _MD_TMPL.render(c=c)


def render_typst(c: InnovationCandidate) -> str:
    return _TYP_TMPL.render(c=c)
