site_name: Aeonis Forge
site_description: A perpetual innovation engine.
site_url: https://aeonisforge.com
repo_url: https://github.com/praniya79/aeonis-forge
repo_name: aeonis-forge

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Posts:
      - posts/index.md
      - "Adaptive Microgrids (demo)": posts/adaptive-microgrids-with-community-incentive-contracts.md
